spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/postgres
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:root}
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgresSQLDialect
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    fromEmail: son.lyhoang2014@gmail.com
    templateId: d-91c3e5444fd04fcca5ba618a7783cb05
    verificationLink: http://localhost:8080/user/confirm-email

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: backend-service
    server: http://localhost:${server.port}
    title: Backend service
    version: 1.0.0

jwt:
  secretKey: abc@123
  expiryMinutes: 5
  expiryDay: 14
  accessKey: 1ef1ed938c82d16798fa1ec4300d3571988b1b37b9116a7e70c6def68bff3516
  refreshKey: 0021f3009a0d7a65b84fd75c056ec4c6a46ca6b9961e7cecfd7ffa38e3fc9dd4
